import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

const response = (data, status = 200) => ({ ok: status < 400, status, json: async () => data })
const members = Array.from({ length: 105 }, (_, i) => ({
  username: `member-${String(i).padStart(3, '0')}`, role: 'user', enabled: true, user_version: `v${i}`,
}))
let store
beforeEach(async () => {
  vi.resetModules()
  vi.useFakeTimers()
  vi.stubGlobal('EventSource', class { addEventListener() {} close() {} })
  vi.stubGlobal('fetch', vi.fn(async () => response({}, 401)))
  store = await import('./store.js')
  await store.initAuth()
  fetch.mockResolvedValue(response({ username: 'operator', can_manage_users: true, runs: [], tasks: [] }))
  await store.login('operator', 'password')
  fetch.mockResolvedValue(response({ users: members }))
  await store.refreshUsers()
  fetch.mockClear()
})
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals() })

describe('用户清单查询', () => {
  it('页外目标仍可核实创建或启停结果，重置结果不能从列表推断', async () => {
    store.setUsersKeyword('member-00')
    store.setUsersPageSize(20)
    fetch.mockImplementation(async (_url, options) => {
      if (options?.method === 'POST') throw new TypeError('response lost')
      return response({ users: members })
    })
    await store.createUser('member-104', 'temporary-password')
    await vi.waitFor(() => expect(store.getState().userCreate.verifyUsername).toBeNull())
    expect(store.getState().userCreate.notice.text).toContain('已有同名用户「member-104」')
    expect(store.getState().userCreate.notice.text).toContain('无法仅凭清单确认')
    store.beginUserAccess('member-104')
    await store.submitUserAccess()
    await store.refreshUsers(true)
    expect(store.getState().userAccess.notice.text).toContain('「member-104」当前已启用')
    store.beginUserReset('member-104')
    await store.resetUserPassword('temporary-password')
    await store.refreshUsers(true)
    expect(store.getState().userReset.notice.text).toContain('清单无法验证密码')
    expect(store.getState().usersQuery).toEqual({ keyword: 'member-00', page: 1, pageSize: 20 })
    expect(fetch.mock.calls.filter(([, options]) => options?.method === 'POST')).toHaveLength(3)
  })

  it.each(['access', 'reset'])('翻页、筛选和刷新不替换 %s 确认目标或版本，成功保留查询位置', async action => {
    store.setUsersPage(8)
    if (action === 'access') store.beginUserAccess('member-070')
    else store.beginUserReset('member-070')
    const original = store.getState()[action === 'access' ? 'userAccess' : 'userReset'].target
    store.setUsersKeyword('member')
    store.setUsersPage(5)
    fetch.mockResolvedValue(response({ users: members.map(user => ({ ...user, user_version: 'new-version' })) }))
    await store.refreshUsers()
    expect(store.getState()[action === 'access' ? 'userAccess' : 'userReset'].target).toEqual(original)
    fetch.mockImplementation(async (_url, options) => options?.method === 'POST'
      ? response({ outcome: 'committed', audit_status: 'recorded' }) : response({ users: members }))
    if (action === 'access') await store.submitUserAccess()
    else await store.resetUserPassword('temporary-password')
    await vi.waitFor(() => expect(store.getState().users.loading).toBe(false))
    const [, options] = fetch.mock.calls.find(([, options]) => options?.method === 'POST')
    expect(JSON.parse(options.body)).toMatchObject({ username: 'member-070', expected_version: 'v70' })
    expect(store.getState().usersQuery).toEqual({ keyword: 'member', page: 5, pageSize: 10 })
  })

  it('读取失败保留查询位置，重试恢复；同身份复核保留，换身份与迟到响应不能带回查询', async () => {
    store.setUsersKeyword('member')
    store.setUsersPageSize(20)
    store.setUsersPage(4)
    fetch.mockRejectedValue(new TypeError('offline'))
    await store.refreshUsers()
    expect(store.getState().users.error).toContain('加载失败')
    expect(store.getState().usersQuery.page).toBe(4)
    fetch.mockResolvedValue(response({ users: members }))
    await store.refreshUsers()
    expect(store.getState().usersQuery.page).toBe(4)
    fetch.mockResolvedValue(response({ username: 'operator', can_manage_users: true }))
    await store.initAuth()
    expect(store.getState().usersQuery.page).toBe(4)
    let release
    fetch.mockImplementationOnce(() => new Promise(resolve => { release = resolve }))
    const oldRead = store.refreshUsers()
    fetch.mockResolvedValue(response({ username: 'second-admin', can_manage_users: true, runs: [], tasks: [] }))
    await store.initAuth()
    release(response({ users: members }))
    await oldRead
    expect(store.getState().usersQuery).toEqual({ keyword: '', page: 1, pageSize: 10 })
    expect(store.getState().users.items).toEqual([])
    store.setUsersKeyword('private search')
    await store.logout()
    expect(store.getState().usersQuery).toEqual({ keyword: '', page: 1, pageSize: 10 })
  })
  it('创建成功保留原查询；主动查看按精确身份定位，保留页大小', async () => {
    const existing = Array.from({ length: 25 }, (_, i) => ({ ...members[i], username: `a${i}-new-user` }))
    const created = { ...members[0], username: 'new-user' }
    fetch.mockImplementation(async (_url, options) => options?.method === 'POST'
      ? response({ outcome: 'committed', audit_status: 'recorded' }, 201)
      : response({ users: [...members, ...existing, created] }))
    store.setUsersKeyword('member')
    store.setUsersPageSize(20)
    store.setUsersPage(3)
    await store.createUser('new-user', 'temporary-password')
    await vi.waitFor(() => expect(store.getState().users.loading).toBe(false))
    expect(store.getState().usersQuery).toEqual({ keyword: 'member', page: 3, pageSize: 20 })
    expect(store.getState().userCreate.createdUsername).toBe('new-user')
    expect(store.showCreatedUser()).toBe(true)
    expect(store.getState().usersQuery).toEqual({ keyword: 'new-user', page: 2, pageSize: 20 })
  })
  it('分页限于展示；关键词或页大小变化回首页，刷新收敛到有效页', async () => {
    expect(store.getState().usersQuery).toEqual({ keyword: '', page: 1, pageSize: 10 })
    store.setUsersPage(99)
    expect(store.getState().usersQuery.page).toBe(11)
    expect(store.getState().users.items).toHaveLength(105)
    store.setUsersKeyword('member')
    expect(store.getState().usersQuery.page).toBe(1)
    for (const size of [20, 50, 100, 10]) {
      store.setUsersPage(2)
      store.setUsersPageSize(size)
      expect(store.getState().usersQuery).toEqual({ keyword: 'member', page: 1, pageSize: size })
    }
    store.setUsersPage(11)
    fetch.mockResolvedValue(response({ users: members.slice(0, 12) }))
    await store.refreshUsers()
    expect(store.getState().usersQuery.page).toBe(2)
    store.setUsersKeyword('no match')
    expect(store.getState().usersQuery.page).toBe(1)
  })
})
